#!/usr/bin/env bash
#Configure your domain zone so that the subdomain www and display information about subdomains

if [ "$#" = 1 ]
then
    subdomains=("www" "lb-01" "web-01" "web-02")
    for sub_domain in "${subdomains[@]}"
    do
	domain_record=$(dig $sub_domain.$1 | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $4}')
        located_at=$(dig $sub_domain.$1 | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $5}')
	echo "The subdomain $sub_domain is a $domain_record record and points to $located_at"
    done
elif [ "$#" = 2 ]
then
    domain_record=$(dig $2.$1 | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $4}')
    located_at=$(dig $2.$1 | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $5}')
    echo "The subdomain $2 is a $domain_record record and points to $located_at"
fi
