#!/usr/bin/env bash
#Script that installs, setup and run the load balancer
#Installs haproxy v2.6

# Update the package list and install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy to use a roundrobin algorithm to route requests to the specified servers
sudo bash -c 'cat > /etc/haproxy/haproxy.cfg <<EOF
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server 117692-web-01 34.229.72.112:80 check
    server 117692-web-02 100.27.3.239:80 check
EOF'

# Restart HAProxy to apply the new configuration
sudo systemctl restart haproxy
