#!/usr/bin/env bash
# Prints "To infinity and beyond" to infinity
# with a sleep 2 between every iteration
# Pirnts 'I am invicinble!!!" in between each iteration

while true
do
echo "To infinity and beyond"
sleep 2
trap 'echo "I am invincible!!!"' SIGTERM
done
