#!/usr/bin/env bash
# Prints numbers up to 100 in list format
# Multiple of 3 prints 'Fizz'
# Multiple of 5 prints 'Buzz'
# Multiple of 3 and 5 prints 'FizzBuzz'
# Otherwise displays the number

for num in {1..100}
do
if (( num % 3 == 0 ))
then
echo "Fizz"
elif (( num % 5 == 0 ))
then
echo "Buzz"
elif (( num % 3 == 0 && num % 5 == 0 ))
then
echo "FizzBuzz"
else
echo "$num"
fi
done
