#!/usr/bin/env bash
# Iterates to 10 and print
# @badluck - Bad luck for 4th iteration
# @goodluck - Good luck for 8th iteration
# @bestschool - for all other iterations

start=0

while [ $start -lt 10 ]
do
if [ $start -eq 3 ]
then
echo "bad luck"
elif [ $start -eq 7 ]
then
echo "good luck"
else
echo "Best School"
fi
(( start++ ))
done
