#!/usr/bin/env bash
# Prints numbers up to 20
# @badluckfromchina - on 4th iteration
# @badluckfromjapan - on 9th iteration
# @badluckfromitaly - on 17th iteration

start=1

while [ $start -le 20 ]
do
echo "$start"
case $start in
"4") echo "bad luck from China";;
"9") echo "bad luck from Japan";;
"17") echo "bad luck from Italy";;
esac
(( start++ ))
done
