#!/usr/bin/env bash
# Run Nginx as Nginx
addgroup --system nginx
adduser --system --no-create-home --disabled-login --ingroup nginx --shell /sbin/nologin nginx
chown -R nginx:nginx /var/cache/nginx /var/log/nginx
sed -i 's/user\s\+root/user nginx/g' /etc/nginx/nginx.conf
sed -i 's/listen\s\+80;/listen 8080;/g' /etc/nginx/sites-enabled/default
nginx -g 'daemon off;' -c /etc/nginx/nginx.conf -u nginx -g nginx
