#!/usr/bin/env bash
# Run Nginx as Nginx

pkill -f apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sed -i "1i user nginx;" /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo -u nginx  systemctl restart nginx
