#!/usr/bin/env bash
# Run Nginx as Nginx
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf 
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
service nginx restart > /dev/null 2>&1
